### ISSUE TITLE
Can't persist user.reg

### ISSUE THREAD

**Issue by erahhal** [emmanuelrosa/sumatrapdf-nix#1]
Nice work here, thanks!

I'm trying to use this to wrap the remarkable tablet desktop app.  I've set up links to `~/.cache` to persist data, and it mostly works.  The login token is not persisted though.  It appears that it's being stored in `user.reg`.  I've created a symlink from a `~/.cache` dir copy of `user.reg` to the `$WINEPREFIX` path, but it gets overwritten every time the app is started.  I think that the `user.reg` file that is there before it gets replaced with the symlink is being read into memory before the link is there, but not sure.

I've also tried linking directly to the files and folders in `~/.wine`.

What is the suggested way to persist this?

**Comment by emmanuelrosa** [comment]
Hi,

I know it's possible to store user.reg in your home directory and symlink it into the WINEPREFIX, because that's what I do with the amazon-kindle package. That application stores some of the settings in user.reg, which of course meant that upon every restart my settings would get reset to their defaults. That is, until I used the symlink technique.

What I've been doing can be seen here: https://github.com/emmanuelrosa/erosanix/blob/master/pkgs/amazon-kindle.nix#L51

 1. Copy user.reg with the "no clobber" flag to where ever you want to persist it. That way, if you've copied it before it won't get overwritten.
 2. Remove user.reg, which as you may recall, will happen in the temporary read/write layer.
 3. Create the symlink.
 4. Run the application.

As long as you set up the symlink before running wine, the symlink should remain in place for the duration of that $WINEPREFIX. Note that `mkWindowsApp` doesn't use ~/.wine for anything. It _always_ creates a temporary $WINEPREFIX.

Something to be aware of is that when you execute wine, it goes into the background, which is unlike most command line programs. For example, if I have a script that looks like this:

```
wine /run/this/app
echo "And then show this message."
```

The program would run and before it terminates, control will be returned to bash and it will execute the next command. Usually that's not what you want. So instead you'd have to do this:

```
wine /run/this/app
wineserver -w
echo "And then show this message."
```

`wineserver -w`  will wait until wine has terminated before returning control to bash. I'm mentioning all of this because `winAppInstall` and `winAppRun` both run `wineserver -w` after your code. That's satisfactory only if you need to run wine once from within those functions. However, if you run multiple wine commands within those functions then you would have to add your own `wineserver -w` commands.

Let me know how it goes packaging the remarkable app :)

**Comment by erahhal** [comment]
Thanks for the detailed explanation!

So I confirmed that `user.cfg` is being copied and linked properly back into the right place.  It seems that somehow the application is not recognizing that the app has already been initialized and re-initializes the registry entries.  There must be some other state that isn't being persisted.  I linked everything in `upper_dir`, so perhaps the app is doing something non-standard.

I'll continue to dig around.  Thanks!

**Comment by emmanuelrosa** [comment]
Another thing to check is the permissions of the files/directories you're linking; Not the link itself, but rather the target. I had a case where I was linking a read-only file, and that prevented the application from persisting its configuration. To my surprise, the application did not report an error.

**Comment by erahhal** [comment]
Permissions are all "write" for my user.  I do see the changes to the `user.reg` file, so at least that one is working.  I've submitted a support request to Remarkable and they are following up with their engineers as to what might be happening, since it's closed source.  The registry entries it needs are there, then it deletes them on start for some reason when running with the wrapper.

It does work across runs if I execute it directly without the wrapper, so the needed state is indeed being written somewhere.  I assume all wine state is maintained in the `.wine` folder?  I did a before and after diff of the `.wine` folder and didn't see any changes that weren't also reflected in the `upper_dir` folder.  strange.

**Comment by emmanuelrosa** [comment]
I came across an issue that may be related to this problem. When I apply changes to system.reg during the installation phase, the changes are saved in the app layer, as expected. However, when the app runs the changes to system.reg are reverted. I suspect the file is getting regenerated from scratch, but I don't know why.

**Comment by erahhal** [comment]
That does appear to be what is happening to me as well.

**Comment by emmanuelrosa** [comment]
I added an experimental attribute to `mkWindowsApp` called `persistRegistry`. When set to `true` it will automatically backup/restore the registry to/from an external file. 

My rational is that perhaps there's something funky going on between Wine and overlayfs; Perhaps something to do with how overlayfs handles inodes. Using regedit to import the registry forces overlayfs to put the registry files in the "upper" layer. That seems to convince Wine that everything is normal :)

I also added an attribute called `fileMap` which you can use to handle the symlinks. Basically, you would simply add the src/dest paths and the rest is handled automatically. You can reference the SumatraPDF package for an example.

**Comment by emmanuelrosa** [comment]
It turns out the root cause was indeed related to overlayfs. You can read about the details here: https://github.com/emmanuelrosa/erosanix/commit/cbf4fc5008b427e01f6bb2b5f10bbe34943c5cb9
